#                                                                        #
# Default routes configuration for the AngularDemo package               #
#                                                                        #

-
  name: 'Welcome screen'
  uriPattern: ''
  defaults:
    '@package':    'Mrimann.AngularDemo'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'

-
  name: 'AngularDemo API :: List of ideas'
  uriPattern: 'api/v1/idea'
  defaults:
    '@package':    'Mrimann.AngularDemo'
    '@controller': 'Api'
    '@format':     'json'

- name: 'AngularDemo API :: Single idea'
  uriPattern: 'api/v1/idea/{idea.__identity}'
  defaults:
    '@package':     'Mrimann.AngularDemo'
    '@controller':  'Api'
    '@format':      'json'
